config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/orders_report'

  devise_for :users

  resources :categories

  resources :products

  resources :orders

  resources :sub_categories

  resources :reviews

  resources :cart_line_items

  resources :addresses

  root to: "categories#index"

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category

  has_many :products

  validates_presence_of :name, :category_id
  validates_uniqueness_of :name
  validates_numericality_of :category_id, minimum: 1

  def formatted_name
    "#{self.id} - #{self.name}"
    #This is used to bring value on each page.
  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController

  before_action :check_is_admin, except: [:index, :show]

  def index
    @sub_categories = SubCategory.all
  end

  def new
    @sub_category = SubCategory.new
  end

  def create
    @sub_category = SubCategory.new(params[:sub_category].permit(:name, :category_id))
    if @sub_category.save
      redirect_to sub_category_path(@sub_category.id), notice: "Successfully added!"
    else
      render action: "new"
    end
  end

  def show
    begin
      @sub_category = SubCategory.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to sub_categories_path, notice: "Record not found :("
    end
  end

  def edit
    @sub_category = SubCategory.find(params[:id])
  end

  def update
    @sub_category = SubCategory.find(params[:id])
    if @sub_category.update_attributes(params[:sub_category].permit(:name, :category_id))
      redirect_to sub_category_path(@sub_category.id), notice: "Successfully updated!"
    else
      render action: "edit"
    end
  end

  def destroy
    @sub_category = SubCategory.find(params[:id])
    @sub_category.destroy
    redirect_to sub_categories_path, notice: "Successfully deleted!!"
  end

end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/edit.html.erb
<h2> Add SubCategory </h2>

<%= form_for @sub_category do |f| %>
<%= f.label :name %><br/>
<%= f.text_field :name %><br/><br/>

<%= f.label :category_id %><br/>
<%= f.text_field :category_id%><br/><br>

<%= f.submit "Submit" %>

<%end%>

app/views/sub_categories/index.html.erb
<h2> Listing SubCategories </h2>

<% if user_signed_in? && current_user.is_admin %>
<%= link_to "Add SubCategory", new_sub_category_path %>
<%end%>

<% if @sub_categories.empty? %>
	<p> Not added yet. </p>
	<% else %>
		<ul>
		<% @sub_categories.each do |sub_category|%>
		<li> <%= link_to sub_category.name, sub_category_path(sub_category.id) %> - 
		<%= sub_category.category_id %>  </li>
		<%end%>
		</ul>
<% end %>

app/views/sub_categories/new.html.erb
<h2> Add SubCategory </h2>

<%= form_for @sub_category do |f| %>
<%= f.label :name %><br/>
<%= f.text_field :name %><br/><br/>

<%= f.label :category_id %><br/>
<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select Category" %><br/><br>

<%= f.submit "Submit" %>

<%end%>

app/views/sub_categories/show.html.erb
<h2><%= @sub_category.name %></h2>

<% if user_signed_in? && current_user.is_admin %>
<%= link_to "Edit", edit_sub_category_path(@sub_category.id) %>
<%= link_to "Destroy", sub_category_path(@sub_category.id), method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

<p>Name : <%= @sub_category.name %> </p>
<p>Category_id : <%= link_to @sub_category.category.name, category_path(@sub_category.category_id) %></p>

<%= link_to "Back", sub_categories_path %>