config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/orders_report'

  devise_for :users

  resources :categories

  resources :products

  resources :orders

  resources :sub_categories

  resources :reviews

  resources :cart_line_items

  resources :addresses

  root to: "categories#index"

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products
  has_many :sub_categories

  validates_presence_of :name
  validates_uniqueness_of :name

  #validates :name, presence: true, uniqueness: true (This method is also used to validate.)

  def formatted_name
    "#{self.id} - #{self.name}"
    #This is used to bring value on each page.
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
=begin
  index
  new
  create
  show
  edit
  update
  destroy
=end
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_is_admin, except: [:index, :show]

  def index
    @categories = Category.all
    #Here '@categories' is the instance variable which will return an array of all objects from the Category model.
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "Successfully created #{@category.name}"
    else
      render action: "new"
    end
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products #This is an instance method. Another way of writing this is #Product.where('category_id = ?', @category.id)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    previous_name = @category.name
    if @category.update_attributes(category_params)
      redirect_to categories_path(@category.id), notice: "Successfully updated from #{previous_name} to #{@category.name}"
    else
      render action: "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, notice: "Successfully deleted #{@category.name}"
  end

  private
  def category_params
    params[:category].permit(:name)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for @category do |f| %>

<% if @category.errors.any? %>
	<h3>Errors </h3>
	<ul>
	<% @category.errors.full_messages.each do |msg|%>
	<li><%= msg %></li>
	<% end %>
	</ul>
	<%end%>

<%= f.label :name %>
<%= f.text_field :name %> <br/> <!--break takes the submit button to the next line -->

<%= f.submit "submit" %> or <%= link_to "back", category_path(@category.id) %> or <%= link_to "List", categories_path %>

	<%end%>

app/views/categories/index.html.erb
<h2>Listing Categories : <%= @categories.length %></h2>

<% if user_signed_in? && current_user.is_admin %>
<%= link_to "Add category", new_category_path %> <!-- target: "_blank" can be used to open link in a new page. -->
<%end%>
	<% if @categories.empty? %>
		<p>Categories have not been added yet. </p>
		<% else %>
		<ol>
			<% @categories.each do |category| %>
			<li><%= link_to category.name, category_path(category.id) %>
				(<%= Product.where('category_id = ?', category.id).length %>)

				<!-- <%= link_to "show", category_path(category.id) %> -->
			</li>
			<% end %>
		</ol>
	<% end %>


 
<!--#Here _blank opens a new page.-->
<!-- new_category_path returns string "/categories/new" -->

<!--<%= link_to "Add category (ror)", "/categories/new" %> |-->

<!--<a href="/categories/new">Add category</a>-->

<%# link_to "Add Product", new_product_path%>

app/views/categories/new.html.erb
<h2>Add Category</h2>

<!--<form action="/categories" method="post"> -->
	<%= form_for @category do |f| %>
	<% if @category.errors.any? %>
	<h3>Errors </h3>
	<ul>
	<% @category.errors.full_messages.each do |msg|%>
	<li><%= msg %></li>
	<% end %>
	</ul>
	<%end%>
	
	<%= f.label :name %> <!-- <label>Name : </label> -->
	<%= f.text_field :name %> <br/>

	<%= f.submit "submit" %>

	<% end %>


<!-- <form action=".." method="post"> 
	<label>Name</label>
	<input type="text">

	<input type="submit">
</form> -->

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>

<% if user_signed_in? && current_user.is_admin %>
<%= link_to "edit", edit_category_path(@category.id)%>
<%= link_to "destroy", category_path(@category.id), method: :delete, data: {confirm: "Are you sure you want to delete?"} %>
	<%end%>
				<% @category.sub_categories.each do |sub_category|%>
				<h4> <%= link_to sub_category.name.upcase %> (<%= sub_category.products.size %>)</h4>
				<ul>
					<% sub_category.products.each do |product|%>
					<li><%= link_to product.name, product_path(product.id)%></li>
					<%end%>
				</ul>
				<%end%>


				<!-- <% if @products.empty? %>
					<p> No products found </p>
					<%else%>

			<ol>
				<% @products.each do |product|%>
				<li> <%= product.name %> INR <%= product.price%> ***** In stock- <%= product.stock%></li>
				<%end%>
			</ol>
				<%end%>


	<%products_less_than_500 = Product.where('price < ? AND category_id = ?',500, @category.id) %>
	<h2> Products less than INR 500: <%= products_less_than_500.count %></h2>
		<% if products_less_than_500.empty? %>
		<p> No products found </p>
		<% else %>
			<ol>
			<% products_less_than_500.each do |product_less_than_500|%>

				<li> <%= product_less_than_500.name %> ***** INR <%= product_less_than_500.price%> </li>
				<%end%>
			</ol>
		<%end%>


	<%products_more_than_500 = Product.where('price > ? AND category_id = ?',500, @category.id) %>
	<h2> Products more than INR 500: <%=products_more_than_500.count%></h2>
		<% if products_more_than_500.empty? %>
		<p> No products found </p>
		<% else %>
			<ol>
			<% products_more_than_500.each do |product_more_than_500| %>
				<li> <%= product_more_than_500.name%> ***** INR <%= product_more_than_500.price%></li>
				<%end%>
			</ol>
<%end%> -->

<%= link_to "Back", categories_path %>