config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/orders_report'

  devise_for :users

  resources :categories

  resources :products

  resources :orders

  resources :sub_categories

  resources :reviews

  resources :cart_line_items

  resources :addresses

  root to: "categories#index"

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :reviews
  has_many :cart_line_items

  belongs_to :category
  belongs_to :sub_category

  has_many :order_products

  #inbuilt validations
  validates_presence_of :name, :price, :category_id, :description, :stock, :sub_category_id
  validates_numericality_of :price, greater_than: 1
  validates_numericality_of :stock, greater_than_or_equal_to: 0
  validates_numericality_of :category_id, :sub_category_id, greater_than: 0
  validates_length_of :description, minimum: 10 #maximum: 100
  validates_length_of :name, minimum: 4
  validate :check_for_cod_based_on_price #invoke custom method
  validate :check_for_category_of_the_product
  validate :check_for_multiple_categories_for_cod

  #custom validations
  def check_for_cod_based_on_price
    if !self.price.nil?
      if self.price > 50000 && self.cod_eligibility
        self.errors.add(:cod_eligibility, "not available for products greater than 50000")
      end
    end
  end

  def check_for_category_of_the_product
    if !self.category_id.nil?
      if self.category_id == 1
        self.errors.add(:cod_eligibility, "Electronics- Not available")
      end
    end
  end

  def check_for_multiple_categories_for_cod
    if !self.category_id.nil?
      if (self.category_id == 1 || self.category_id == 4) && self.cod_eligibility
        self.errors.add(:cod_eligibility, "Not available for this category")
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_is_admin, except: [:index, :show]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product.id), notice: "Successfully created a product."
    else
      render action: "new"
    end
  end

  def show
    @review = Review.new
    @cart_line_item = CartLineItem.new
    begin
      @product = Product.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to products_path, notice: "Record Not Found"
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to product_path(@product.id), notice: "Successfully updated the product"
    else
      render action: "edit"
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice: "Successfully deleted #{@product.name}"
  end

  private
  def product_params
    params[:product].permit(:name, :description, :price, :category_id, :stock, :cod_eligibility, :image_url, :sub_category_id)
  end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h2> Edit Category </h2>

<%= form_for @product do |f| %>
	<% if @product.errors.any? %>
	<h3> Errors : </h3>
	<ul>
	<% @product.errors.full_messages.each do |msg| %>
	<li> <%= msg %></li>
	<% end %>
	</ul>
	<%end%>

	<%= f.label :name %> <br/>
	<%= f.text_field :name %><br/>

	<%= f.label :description %><br/>
	<%= f.text_area :description, rows:15, cols: 50 %><br/>

	<%= f.label :price %><br/>
	<%= f.text_field :price %><br/>

	<%= f.label :category_id %><br/>
	<%= f.collection_select :category_id, Category.all, :id, :formatted_name, prompt: "Select Category" %><br/> <!-- Here we can also use :formatted_name (method defined in models) as the third attribute. The :id refers to the primary key of source-->

	<%= f.label :sub_category_id %><br/>
	<%= f.collection_select :sub_category_id, SubCategory.all, :id, :formatted_name, prompt: "Select SubCategory" %><br/>

	<%= f.label :stock %><br/>
	<%= f.text_field :stock %><br/>

	<%= f.label :cod_eligibility %><br/>
	<%= f.check_box :cod_eligibility %><br/>

	<%= f.label :image_url %><br/>
	<%= f.text_field :image_url %><br/>

	<%= f.submit "submit" %>

<%end%>

app/views/products/index.html.erb
<h2>Listing Products : <%= @products.length %></h2>

<% if user_signed_in? && current_user.is_admin %>
<%= link_to "Add product", new_product_path %>
<%end%>

	<% if @products.empty? %>
		<p>No products found </p>
		<% else %>
		<ul>
			<% @products.each do |product| %>
			<li><%= link_to product.name, product_path(product.id) %>
			INR <%= product.price %> -- <%= product.category.name %></li>
			<% end %>
		</ul>
	<%end%>

app/views/products/index.xls.erb
<table border="1">
	<thead>
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Price(INR)</th>
			<th>Category</th>
		</tr>
	</thead>
<tbody>
	<% @products.each_with_index do |product, index| %>
		<tr>
			<td><%= index + 1 %></td>
			<td><%= product.name %></td>
			<td><%= product.price %></td>
			<td><%= product.category.name %></td>
			</tr>
		<%end%>
	</tbody>
</table>

app/views/products/new.html.erb
<h2>Add Product</h2>
<%= form_for @product do |f| %>
	<% if @product.errors.any? %>
	<h3> Errors: </h3>
		<ul>
			<% @product.errors.full_messages.each do |msg|%>
			<li> <%= msg %></li>
			<%end%>
		</ul>
	<%end%>

<%= f.label :name %> <br/>
<%= f.text_field :name %><br/>

<%= f.label :description %><br/>
<%= f.text_area :description, rows:15, cols: 50 %><br/>

<%= f.label :price %><br/>
<%= f.text_field :price %><br/>

<%= f.label :category_id %><br/>
<%= f.collection_select :category_id, Category.all, :id, :formatted_name, prompt: "Select Category" %><br/> <!-- Here we can also use :formatted_name (method defined in models) as the third attribute. The :id refers to the primary key of source-->

<%= f.label :sub_category_id %><br/>
<%= f.collection_select :sub_category_id, SubCategory.all, :id, :formatted_name, prompt: "Select SubCategory" %><br/>

<%= f.label :stock %><br/>
<%= f.text_field :stock %><br/>

<%= f.label :cod_eligibility %><br/>
<%= f.check_box :cod_eligibility %><br/>

<%= f.label :image_url %><br/>
<%= f.text_field :image_url %><br/>

<%= f.submit "submit" %>

<%end%>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>

<% if user_signed_in? && current_user.is_admin %>
<%= link_to "edit", edit_product_path(@product.id) %>
<%= link_to "destroy", product_path(@product.id), method: :delete, data: {confirm: "Are you sure?"} %>
<%end%>

<p>Price: <%= @product.price %></p>
<p>Description: <%= @product.description %></p>
<p>Stock: <%= @product.stock %></p>
<p>Cod Eligibility: <%= @product.cod_eligibility %></p>
<p>Category Id: <%= link_to @product.category.name, category_path(@product.category_id)%> <!--Another way of displaying the data is -> --><!--<%= Category.find(@product.category_id).name %></p>--> <br/>

<p>Sub Category : <%= link_to @product.sub_category.name %></p>

<%= form_for @cart_line_item do |f| %>

<%= f.label :quantity %><br/>
<%= f.select :quantity, [1,2,3,4,5]%><br/> <!--another way of doing this is (1..5).to_a -->

<%= f.hidden_field :product_id, value: @product.id %>

<%= f.submit "Add to cart" %>

<%end%>


<h2>Reviews : ( <%= @product.reviews.length %> ) </h2>

<ol>
	<%@product.reviews.each do |review| %>
	<li>
		<%= review.user.email %> rated <%= review.rating %> <br/>
		<%= review.title %> - <%= review.body %> on <%= review.created_at %> <br/>

		<% if user_signed_in? && review.user_id == current_user.id %>
		<%= link_to "delete", review_path(review.id), method: :delete, data: {confirm: "Are you sure?"} %>
		<%end%>
	</li>
	<%end%>
</ol>


<h3>Add Review</h3>
<%= form_for @review do |f| %>

<%= f.label :rating %> <br/>
<%= f.radio_button :rating, 1 %> 1
<%= f.radio_button :rating, 2 %> 2
<%= f.radio_button :rating, 3 %> 3
<%= f.radio_button :rating, 4 %> 4
<%= f.radio_button :rating, 5 %> 5
<br/>

<%= f.label :title %><br/>
<%= f.text_field :title %><br/>

<%= f.label :body %><br/>
<%= f.text_area :body %><br/>

<%= f.hidden_field :product_id, value: @product.id %>

<%#= f.hidden_field :user_id, value: current_user.id (We will NOT give these details here since the user credentials can easily be altered. We will authenticate the user in create method)%>

<%= f.submit %>

<%end%>


<%= link_to "Back", products_path %>