config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/orders_report'

  devise_for :users

  resources :categories

  resources :products

  resources :orders

  resources :sub_categories

  resources :reviews

  resources :cart_line_items

  resources :addresses

  root to: "categories#index"

end

app/models/address.rb
class Address < ActiveRecord::Base

  validates_presence_of :street, :city, :pin, :title
  validates_numericality_of :user_id, :pin, greater_than: 0

  has_many :orders
  belongs_to :user

  def full_address

    "#{self.street}, #{self.city} - #{self.pin}"
  end

end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base

  belongs_to :product
  belongs_to :user

  validates_presence_of :product_id, :user_id, :quantity
  validates_numericality_of :product_id, :user_id, greater_than: 0
  validates_numericality_of :quantity, within: 1..5

  def save_or_update
    line_item = CartLineItem.find_by(user_id: self.user_id, product_id: self.product_id)
    if line_item.nil?
      self.save
    else
      line_item.update_attributes(quantity: line_item.quantity + self.quantity)
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products
  has_many :sub_categories

  validates_presence_of :name
  validates_uniqueness_of :name

  #validates :name, presence: true, uniqueness: true (This method is also used to validate.)

  def formatted_name
    "#{self.id} - #{self.name}"
    #This is used to bring value on each page.
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates_presence_of :user_id, :order_date, :order_number
  validates_numericality_of :user_id, greater_than:0

  before_validation :set_order_details

  belongs_to :user

  belongs_to :address

  has_many :order_products

  after_create :generate_order_products

  after_create :send_confirmation

  def generate_order_products
    #CartLineItem.where('user_id - ?', self.user_id)
    cart_line_items = self.user.cart_line_items
    sum = 0
    cart_line_items.each do |cart_line_item|
      order_product = OrderProduct.new
      order_product.order_id = self.id
      order_product.product_id = cart_line_item.product_id
      order_product.quantity = cart_line_item.quantity
      order_product.price = cart_line_item.product.price
      order_product.total = order_product.price * order_product.quantity
      order_product.save
      sum += order_product.total
    end
    #removes products from cart line items
    CartLineItem.delete(self.user.cart_line_items.pluck(:id))
    self.update_attributes(total_amoun: sum)
  end

  def set_order_details
    self.order_number = "DCT#{Random.rand(1000)}"
    self.order_date = Date.today
    #self.total_amoun = 1 #todo
  end

  def send_confirmation
    Notification.order_confirmation(self).deliver!
  end

end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base

  belongs_to :product
  belongs_to :order

  validates_presence_of :order_id, :product_id, :quantity, :price, :total
  validates_numericality_of :order_id, :product_id, :quantity, :price, :total, greater_than: 0


end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :reviews
  has_many :cart_line_items

  belongs_to :category
  belongs_to :sub_category

  has_many :order_products

  #inbuilt validations
  validates_presence_of :name, :price, :category_id, :description, :stock, :sub_category_id
  validates_numericality_of :price, greater_than: 1
  validates_numericality_of :stock, greater_than_or_equal_to: 0
  validates_numericality_of :category_id, :sub_category_id, greater_than: 0
  validates_length_of :description, minimum: 10 #maximum: 100
  validates_length_of :name, minimum: 4
  validate :check_for_cod_based_on_price #invoke custom method
  validate :check_for_category_of_the_product
  validate :check_for_multiple_categories_for_cod

  #custom validations
  def check_for_cod_based_on_price
    if !self.price.nil?
      if self.price > 50000 && self.cod_eligibility
        self.errors.add(:cod_eligibility, "not available for products greater than 50000")
      end
    end
  end

  def check_for_category_of_the_product
    if !self.category_id.nil?
      if self.category_id == 1
        self.errors.add(:cod_eligibility, "Electronics- Not available")
      end
    end
  end

  def check_for_multiple_categories_for_cod
    if !self.category_id.nil?
      if (self.category_id == 1 || self.category_id == 4) && self.cod_eligibility
        self.errors.add(:cod_eligibility, "Not available for this category")
      end
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  validates_presence_of :product_id, :user_id, :title, :rating
  validates_numericality_of :product_id, :user_id, greater_than: 0
  validates_numericality_of :rating, within: 1..5 #inclusive range. If '...' it will be exclusive range (1...5) will give (1,2,3,4)
  validates_length_of :body, minimum: 10, allow_blank: true
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category

  has_many :products

  validates_presence_of :name, :category_id
  validates_uniqueness_of :name
  validates_numericality_of :category_id, minimum: 1

  def formatted_name
    "#{self.id} - #{self.name}"
    #This is used to bring value on each page.
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :cart_line_items
  has_many :orders
  has_many :addresses

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username, :mobile, :gender
  validates_numericality_of :mobile
  validates_length_of :mobile, is: 10
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user!

  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    #@order.set_order_details
    if @order.save
      redirect_to order_path(@order.id), notice: "Your order has been placed"
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def order_params
    #params[:order].permit()
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!

  def index
    @reviews = current_user.reviews
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to :back, notice: "Thank you for the review"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product_id), notice: "Deleted"
  end

  private
  def review_params
    params[:review].permit(:title, :body, :rating, :product_id)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_line_items_helper.rb
module CartLineItemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>


	Welcome <%= current_user.username %> | 

			<%if current_user.is_admin%>
			<%= link_to "Dashboard", dashboard_index_path %> | 
			<%end%>

			<%= link_to "My cart", cart_line_items_path %> 
			(<%= "#{current_user.cart_line_items.size}"%>) | 

			<%= link_to "My orders", orders_path%> | 

			<%= link_to "My addresses", addresses_path %> | 

			<%= link_to "My Reviews", reviews_path %> | 

			<%= link_to "Account Setting", edit_user_registration_path%> | 

			<%= link_to "Logout", destroy_user_session_path, method: :delete%>
<%else%>
<%= link_to "Login", new_user_session_path %> | <%= link_to "Register", new_user_registration_path %>
<%end%><br/> <br/>

<%= link_to "Categories", categories_path %> | <%= link_to "Sub_Categories", sub_categories_path %> | <%= link_to "Products", products_path %> <br/>
<br/>


<%= notice %>
<%= alert %>
<%= yield %>

</body>
</html>

app/views/notification/order_confirmation.html.erb
<h1>Notification#order_confirmation</h1>

<p>Hello <%= @order.user.username %></p>

<h2>Your order has been place</h2>
<p>  # : <%= @order.order_number %></p>
<p>  Date : <%= @order.order_date %> </p>
<p>  Total : <%= @order.total_amoun %> </p>

<h2>Your line items</h2>
<table border="1">
    <thead>
        <tr>
            <th> # </th>
            <th> Product </th>
            <th> Price </th>
            <th> Quantity </th>
            <th> Total </th>
        </tr>
    </thead>

    <tbody>
        <% @order.order_products.each_with_index do |order_product, index| %>
            <tr>   
                <td><%= index + 1 %></td>
                <td><%= order_product.product.name %></td>
                <td><%= order_product.price %></td>
                <td><%= order_product.quantity %> </td>
                <% total = order_product.price * order_product.quantity %>
                <td><%= total %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<a href="#">Unsubscribe</a>

app/views/notification/order_confirmation.text.erb
Notification#order_confirmation

<%= @greeting %>, find me in app/views/notification/order_confirmation.text.erb